# Generated by Django 4.0.1 on 2022-03-29 14:42

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('semester', models.CharField(choices=[('FALL', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('WINTER', 'Winter')], max_length=10)),
                ('year', models.DecimalField(decimal_places=0, max_digits=5)),
                ('code', models.CharField(max_length=30)),
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.EmailField(max_length=120)),
                ('course_id', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.EmailField(max_length=120)),
                ('team_id', models.DecimalField(decimal_places=0, max_digits=20)),
                ('course_id', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_name', models.CharField(max_length=120)),
                ('student_list', multiselectfield.db.fields.MultiSelectField(choices=[('Hannah', 'Hannah Brooks'), ('Zach', 'Zach Crews'), ('Matthew', 'Matthew Scott'), ('Fred', 'Fred Pan'), ('Alec', 'Alec Lobanov'), ('Yufan', 'Yufan Yang')], max_length=35)),
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
