# Generated by Django 4.0.1 on 2022-03-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.EmailField(default=str, max_length=120),
            preserve_default=False,
        ),
    ]
