# Generated by Django 4.0.3 on 2022-03-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='course',
            new_name='team_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.AddField(
            model_name='team',
            name='student_list',
            field=models.CharField(choices=[('email', 'Email'), ('chat', 'Chat'), ('call', 'Call')], default='', max_length=120),
        ),
    ]
