# Generated by Django 4.0.3 on 2022-03-23 19:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_course_team_team_name_remove_team_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='student_list',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('email', 'Email'), ('chat', 'Chat'), ('call', 'Call')], max_length=15),
        ),
    ]
