# Generated by Django 4.0.1 on 2022-04-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_invitation_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='course_name',
            field=models.CharField(default='Retired course', max_length=120),
            preserve_default=False,
        ),
    ]
