# Generated by Django 4.0.1 on 2022-04-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_course_name_invitation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='course_id',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=20),
        ),
        migrations.AddField(
            model_name='team',
            name='team_num',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
