# Generated by Django 4.0.1 on 2022-04-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_team_id_registration_team_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='team_num',
            new_name='team_id',
        ),
    ]
