# Generated by Django 4.0.1 on 2022-04-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_team_num_registration_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='student_list',
        ),
    ]
