
# Generated by Django 4.0.1 on 2022-04-06 15:49

# Generated by Django 4.0.1 on 2022-04-06 15:29


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_peerassessment_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=256)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.submission')),
            ],
        ),
    ]
