# Generated by Django 4.0.1 on 2022-04-06 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_freeresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='survey',
            new_name='peer_assessment',
        ),
        migrations.RemoveField(
            model_name='freeresponse',
            name='submission',
        ),
        migrations.AddField(
            model_name='freeresponse',
            name='peer_assessment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assessments.peerassessment'),
        ),
    ]
