# Generated by Django 4.0.1 on 2022-04-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_rename_survey_submission_peer_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerassessment',
            name='course_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
