# Generated by Django 4.0.1 on 2022-05-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_submission_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
