# Generated by Django 3.2.12 on 2022-05-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_freeresponseanswer_free_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerassessment',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
